server:
  port: 8089

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://127.0.0.1:3306/20067?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: feign
      sensitiveHeaders: "*"
  host:
    socket-timeout-millis: 1200
    connect-timeout-millis: 1200


