server:
  port: 8085

spring:
  application:
    name: feign
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

feign:
  hystrix:
    enabled: true
